# Generated by Django 4.2.7 on 2026-04-27 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FOOD', 'Food & Groceries'), ('CLOTHING', 'Clothing & Fashion'), ('HOUSEHOLD', 'Household Items'), ('HEALTH', 'Health & Beauty'), ('AUTOMOTIVE', 'Automotive'), ('SPORTS', 'Sports & Fitness'), ('BOOKS', 'Books & Stationery'), ('AGRICULTURE', 'Agriculture'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(default='piece', help_text='e.g. kg, liter, piece, pack', max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Ethiopian Birr (ETB)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability', models.BooleanField(default=True, help_text='Whether the product is currently in stock')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, help_text='Current stock quantity (optional)', null=True)),
                ('notes', models.CharField(blank=True, help_text='e.g. "Imported", "Local brand", "Expires soon"', max_length=300, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Shop Product',
                'verbose_name_plural': 'Shop Products',
                'ordering': ['price'],
            },
        ),
    ]
