# Generated by Django 4.2.7 on 2026-04-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_226e74_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='shopproduct',
            index=models.Index(fields=['shop', 'availability'], name='products_sh_shop_id_3b4fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='shopproduct',
            index=models.Index(fields=['product', 'availability'], name='products_sh_product_43a696_idx'),
        ),
        migrations.AddIndex(
            model_name='shopproduct',
            index=models.Index(fields=['price'], name='products_sh_price_6bab8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopproduct',
            unique_together={('shop', 'product')},
        ),
    ]
