# Generated by Django 4.2.7 on 2026-04-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'SHOP_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['city', 'is_approved', 'is_active'], name='shops_shop_city_697ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='shops_shop_latitud_e4840a_idx'),
        ),
    ]
