# Generated by Django 4.2.7 on 2026-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('category_filter', models.CharField(blank=True, max_length=50, null=True)),
                ('city_filter', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop View',
                'verbose_name_plural': 'Shop Views',
                'ordering': ['-created_at'],
            },
        ),
    ]
