# Generated by Django 4.2.7 on 2026-04-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('products', '0002_initial'),
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product'),
        ),
        migrations.AddField(
            model_name='productview',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query'], name='analytics_s_query_86cb43_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['created_at'], name='analytics_s_created_269249_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'created_at'], name='analytics_p_product_347452_idx'),
        ),
    ]
