# Generated by Django 4.2.7 on 2026-04-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['shop', 'rating'], name='reviews_rev_shop_id_06e1fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'shop')},
        ),
    ]
