# Generated by Django 4.2.7 on 2026-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PRICE_DROP', 'Price Drop'), ('BACK_IN_STOCK', 'Back in Stock'), ('NEW_SHOP', 'New Shop Nearby'), ('TRENDING', 'Trending Product'), ('SHOP_APPROVED', 'Shop Approved'), ('SHOP_REJECTED', 'Shop Rejected'), ('NEW_REVIEW', 'New Review'), ('SYSTEM', 'System Message')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_product_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_shop_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
